version: '3.8'

services:
  postgres-clientepersona:
    image: postgres:15
    container_name: postgres-clientepersona
    environment:
      POSTGRES_DB: clientepersona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - banco-net

  postgres-cuentamovimiento:
    image: postgres:15
    container_name: postgres-cuentamovimiento
    environment:
      POSTGRES_DB: cuentamovimiento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - banco-net

  cliente-persona:
    build: ./cliente-persona
    container_name: cliente-persona
    depends_on:
      - postgres-clientepersona
      - kafka
    ports:
      - "8080:8080"
    networks:
      - banco-net

  cuenta-movimiento:
    build: ./cuenta-movimiento
    container_name: cuenta-movimiento
    depends_on:
      - postgres-cuentamovimiento
      - cliente-persona
      - kafka
    ports:
      - "8081:8081"
    networks:
      - banco-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - banco-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - banco-net

networks:
  banco-net:
    driver: bridge
